### ISSUE TITLE
Add support for the buttons on the dev board

### ISSUE THREAD

**Issue by hannobraun** [braun-embedded/rust-dwm1001#18]
Both are connected to pins on the nRF52. They should be supported in the same way that the LEDs are explicitely supported.

**Comment by jamesmunns** [comment]
As a note, I believe one of the buttons is tied to the reset pin of the device, so only one pin can be used in user context.

**Comment by hannobraun** [comment]
Closing in favor of https://github.com/braun-embedded/rust-dw1000/issues/104.
